Collections:
- Name: SDMGR
  Metadata:
    Training Data: KIEDataset
    Training Techniques:
      - Adam
    Training Resources: 1x NVIDIA A100-SXM4-80GB
    Architecture:
      - UNet
      - SDMGRHead
  Paper:
    URL: https://arxiv.org/abs/2103.14470.pdf
    Title: 'Spatial Dual-Modality Graph Reasoning for Key Information Extraction'
  README: configs/kie/sdmgr/README.md

Models:
  - Name: sdmgr_unet16_60e_wildreceipt
    In Collection: SDMGR
    Config: configs/kie/sdmgr/sdmgr_unet16_60e_wildreceipt.py
    Metadata:
      Training Data: wildreceipt
    Results:
      - Task: Key Information Extraction
        Dataset: wildreceipt
        Metrics:
          macro_f1: 0.890
    Weights: https://download.openmmlab.com/mmocr/kie/sdmgr/sdmgr_unet16_60e_wildreceipt/sdmgr_unet16_60e_wildreceipt_20220825_151648-22419f37.pth
